require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CustomProductsController do

  # This should return the minimal set of attributes required to create a valid
  # CustomProduct. As you add validations to CustomProduct, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CustomProductsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all custom_products as @custom_products" do
      custom_product = CustomProduct.create! valid_attributes
      get :index, {}, valid_session
      assigns(:custom_products).should eq([custom_product])
    end
  end

  describe "GET show" do
    it "assigns the requested custom_product as @custom_product" do
      custom_product = CustomProduct.create! valid_attributes
      get :show, {:id => custom_product.to_param}, valid_session
      assigns(:custom_product).should eq(custom_product)
    end
  end

  describe "GET new" do
    it "assigns a new custom_product as @custom_product" do
      get :new, {}, valid_session
      assigns(:custom_product).should be_a_new(CustomProduct)
    end
  end

  describe "GET edit" do
    it "assigns the requested custom_product as @custom_product" do
      custom_product = CustomProduct.create! valid_attributes
      get :edit, {:id => custom_product.to_param}, valid_session
      assigns(:custom_product).should eq(custom_product)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CustomProduct" do
        expect {
          post :create, {:custom_product => valid_attributes}, valid_session
        }.to change(CustomProduct, :count).by(1)
      end

      it "assigns a newly created custom_product as @custom_product" do
        post :create, {:custom_product => valid_attributes}, valid_session
        assigns(:custom_product).should be_a(CustomProduct)
        assigns(:custom_product).should be_persisted
      end

      it "redirects to the created custom_product" do
        post :create, {:custom_product => valid_attributes}, valid_session
        response.should redirect_to(CustomProduct.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved custom_product as @custom_product" do
        # Trigger the behavior that occurs when invalid params are submitted
        CustomProduct.any_instance.stub(:save).and_return(false)
        post :create, {:custom_product => {}}, valid_session
        assigns(:custom_product).should be_a_new(CustomProduct)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CustomProduct.any_instance.stub(:save).and_return(false)
        post :create, {:custom_product => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested custom_product" do
        custom_product = CustomProduct.create! valid_attributes
        # Assuming there are no other custom_products in the database, this
        # specifies that the CustomProduct created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CustomProduct.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => custom_product.to_param, :custom_product => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested custom_product as @custom_product" do
        custom_product = CustomProduct.create! valid_attributes
        put :update, {:id => custom_product.to_param, :custom_product => valid_attributes}, valid_session
        assigns(:custom_product).should eq(custom_product)
      end

      it "redirects to the custom_product" do
        custom_product = CustomProduct.create! valid_attributes
        put :update, {:id => custom_product.to_param, :custom_product => valid_attributes}, valid_session
        response.should redirect_to(custom_product)
      end
    end

    describe "with invalid params" do
      it "assigns the custom_product as @custom_product" do
        custom_product = CustomProduct.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CustomProduct.any_instance.stub(:save).and_return(false)
        put :update, {:id => custom_product.to_param, :custom_product => {}}, valid_session
        assigns(:custom_product).should eq(custom_product)
      end

      it "re-renders the 'edit' template" do
        custom_product = CustomProduct.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CustomProduct.any_instance.stub(:save).and_return(false)
        put :update, {:id => custom_product.to_param, :custom_product => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested custom_product" do
      custom_product = CustomProduct.create! valid_attributes
      expect {
        delete :destroy, {:id => custom_product.to_param}, valid_session
      }.to change(CustomProduct, :count).by(-1)
    end

    it "redirects to the custom_products list" do
      custom_product = CustomProduct.create! valid_attributes
      delete :destroy, {:id => custom_product.to_param}, valid_session
      response.should redirect_to(custom_products_url)
    end
  end

end
