require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PrintsController do

  # This should return the minimal set of attributes required to create a valid
  # Print. As you add validations to Print, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PrintsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all prints as @prints" do
      print = Print.create! valid_attributes
      get :index, {}, valid_session
      assigns(:prints).should eq([print])
    end
  end

  describe "GET show" do
    it "assigns the requested print as @print" do
      print = Print.create! valid_attributes
      get :show, {:id => print.to_param}, valid_session
      assigns(:print).should eq(print)
    end
  end

  describe "GET new" do
    it "assigns a new print as @print" do
      get :new, {}, valid_session
      assigns(:print).should be_a_new(Print)
    end
  end

  describe "GET edit" do
    it "assigns the requested print as @print" do
      print = Print.create! valid_attributes
      get :edit, {:id => print.to_param}, valid_session
      assigns(:print).should eq(print)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Print" do
        expect {
          post :create, {:print => valid_attributes}, valid_session
        }.to change(Print, :count).by(1)
      end

      it "assigns a newly created print as @print" do
        post :create, {:print => valid_attributes}, valid_session
        assigns(:print).should be_a(Print)
        assigns(:print).should be_persisted
      end

      it "redirects to the created print" do
        post :create, {:print => valid_attributes}, valid_session
        response.should redirect_to(Print.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved print as @print" do
        # Trigger the behavior that occurs when invalid params are submitted
        Print.any_instance.stub(:save).and_return(false)
        post :create, {:print => {}}, valid_session
        assigns(:print).should be_a_new(Print)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Print.any_instance.stub(:save).and_return(false)
        post :create, {:print => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested print" do
        print = Print.create! valid_attributes
        # Assuming there are no other prints in the database, this
        # specifies that the Print created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Print.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => print.to_param, :print => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested print as @print" do
        print = Print.create! valid_attributes
        put :update, {:id => print.to_param, :print => valid_attributes}, valid_session
        assigns(:print).should eq(print)
      end

      it "redirects to the print" do
        print = Print.create! valid_attributes
        put :update, {:id => print.to_param, :print => valid_attributes}, valid_session
        response.should redirect_to(print)
      end
    end

    describe "with invalid params" do
      it "assigns the print as @print" do
        print = Print.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Print.any_instance.stub(:save).and_return(false)
        put :update, {:id => print.to_param, :print => {}}, valid_session
        assigns(:print).should eq(print)
      end

      it "re-renders the 'edit' template" do
        print = Print.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Print.any_instance.stub(:save).and_return(false)
        put :update, {:id => print.to_param, :print => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested print" do
      print = Print.create! valid_attributes
      expect {
        delete :destroy, {:id => print.to_param}, valid_session
      }.to change(Print, :count).by(-1)
    end

    it "redirects to the prints list" do
      print = Print.create! valid_attributes
      delete :destroy, {:id => print.to_param}, valid_session
      response.should redirect_to(prints_url)
    end
  end

end
